create table bookings (
    id CHAR(36) primary key,
    course_id CHAR(36) not null,
    tutor_id CHAR(36) not null,
    student_id CHAR(36) not null,
    class_type VARCHAR(255) not null,
    booking_date DATE not null,
    booking_time TIME not null,
    timezone VARCHAR(50) not null,
    latitude DECIMAL(8, 6) not null,
    longitude DECIMAL(9, 6) not null,
    notes_tutor VARCHAR(255) null,
    notes_student VARCHAR(255) null,
    status VARCHAR(255) not null,
    expired_at timestamp not null,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp on update current_timestamp,
    deleted_at timestamp null,
    created_by CHAR(36) not null,
    updated_by CHAR(36) not null,
    deleted_by CHAR(36) null,
    INDEX idx_tutor_id (tutor_id),
    INDEX idx_student_id (student_id),
    INDEX idx_booking_date (booking_date),
    INDEX idx_booking_time (booking_time),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),

    CONSTRAINT fk_course_id FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_tutor_id FOREIGN KEY (tutor_id) REFERENCES tutors(id),
    CONSTRAINT fk_student_id FOREIGN KEY (student_id) REFERENCES students(id)
);
