CREATE TABLE course_drafts (
    id CHAR(36) NOT NULL PRIMARY KEY,
    course_id CHAR(36) NOT NULL,
    draft_data JSON NOT NULL,
    draft_type ENUM('edit', 'create') NOT NULL DEFAULT 'edit',
    status ENUM('draft', 'pending_approval', 'approved', 'rejected') NOT NULL DEFAULT 'draft',
    created_by CHAR(36) NOT NULL,
    submitted_at TIMESTAMP NULL,
    reviewed_at TIMESTAMP NULL,
    reviewed_by CHAR(36) NULL,
    review_notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    updated_by CHAR(36) NULL,
    deleted_by CHAR(36) NULL,
    FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users (id),
    FOREIGN KEY (reviewed_by) REFERENCES users (id),
    INDEX idx_course_drafts_course_id (course_id),
    INDEX idx_course_drafts_status (status),
    INDEX idx_course_drafts_created_by (created_by),
    INDEX idx_course_drafts_deleted_at (deleted_at),
    INDEX idx_course_drafts_submitted_at (submitted_at),
    UNIQUE KEY unique_active_draft_per_course (course_id, status, deleted_at)
);
